// <auto-generated />
using System;
using BD.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BD.Migrations
{
    [DbContext(typeof(TropicFruitXportContext))]
    partial class TropicFruitXportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BD.Model.Departamento", b =>
                {
                    b.Property<string>("codDepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codDirector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreDpto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codDepto");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("BD.Model.Empleado", b =>
                {
                    b.Property<string>("nDIEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cargoE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeDepto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("comisionE")
                        .HasColumnType("real");

                    b.Property<DateTime>("fecIncorporacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("jefeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("salEmp")
                        .HasColumnType("real");

                    b.Property<string>("seEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nDIEmp");

                    b.HasIndex("codeDepto");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("BD.Model.Empleado", b =>
                {
                    b.HasOne("BD.Model.Departamento", "departamentos")
                        .WithMany("Empleados")
                        .HasForeignKey("codeDepto");

                    b.Navigation("departamentos");
                });

            modelBuilder.Entity("BD.Model.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
